### ISSUE TITLE
ValueError: object has no __init__ method

### ISSUE THREAD

**Issue by 2f2a** [pykalman/pykalman#106]
Hi well I was attempting the 1st example on https://pykalman.github.io/ (the dead-simple one), But:
```
Python 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pykalman import KalmanFilter
>>> import numpy as np
>>> kf = KalmanFilter(transition_matrices = [[1, 1], [0, 1]], observation_matrices = [[0.1, 0.5], [-0.3, 0.0]])
>>> measurements = np.asarray([[1,0], [0,0], [0,1]])  # 3 observations
>>> kf = kf.em(measurements, n_iter=5)
Traceback (most recent call last):
  File "/home/per/nice_ML/nice_ML_PB_pythons/lib/python3.11/site-packages/pykalman/utils.py", line 111, in get_params
    args = inspect.getargspec(obj.__init__)[0]
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/per/nice_ML/nice_ML_PB_pythons/lib/python3.11/site-packages/pykalman/standard.py", line 1365, in em
    self._initialize_parameters()
  File "/home/per/nice_ML/nice_ML_PB_pythons/lib/python3.11/site-packages/pykalman/standard.py", line 1483, in _initialize_parameters
    arguments = get_params(self)
                ^^^^^^^^^^^^^^^^
  File "/home/per/nice_ML/nice_ML_PB_pythons/lib/python3.11/site-packages/pykalman/utils.py", line 118, in get_params
    raise ValueError("object has no __init__ method")
ValueError: object has no __init__ method

pip list | grep pykal
pykalman                      0.9.5
```

**Comment by pranavlal** [comment]
Hi,
I have exactly the same problem. There has been a change in python which has lead to this  situation. See the below link for details. 
[invoke issues](https://github.com/pyinvoke/invoke/issues/833) 

I do not know how to fix the problem, downgrading python is difficult in my situation. The pykalman package is unusable.

**Comment by franko-franicevich** [comment]
Yeah, same problem here. Looking at the commits, this project has seen no activity for 9 years, and may be dead.
Looking at pull requests on this repo, you can see someone has generously provided a fix, but has had no reaction on their pull request. However, a user has published a new package with that fix:

Check here:

https://github.com/pykalman/pykalman/pull/101

**Comment by fkiraly** [comment]
Should be resolved by https://github.com/pykalman/pykalman/pull/110
