### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by sanjayankur31** [pykalman/pykalman#50]
I've been trying to update the Fedora package, and some tests seem to be failing:

```
+ nosetests pykalman/tests/
..E./builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/standard.py:1397: UserWarning: transition_offsets has 2 dimensions now; after fitting, it will have dimension 1
  warnings.warn(warn_str)
E............
======================================================================
ERROR: test_kalman_fit (pykalman.tests.test_standard.KalmanFilterTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/tests/test_standard.py", line 128, in test_kalman_fit
    loglikelihoods[i] = kf.loglikelihood(self.data.observations)
  File "/builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/standard.py", line 1474, in loglikelihood
    predicted_state_means, predicted_state_covariances, Z
  File "/builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/standard.py", line 170, in _loglikelihoods
    predicted_observation_covariance[np.newaxis, :, :]
  File "/builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/utils.py", line 73, in log_multivariate_normal_density
    cv_sol = solve_triangular(cv_chol, (X - mu).T, lower=True).T
  File "/usr/lib64/python2.7/site-packages/scipy/linalg/basic.py", line 155, in solve_triangular
    b1 = _asarray_validated(b, check_finite=check_finite)
  File "/usr/lib64/python2.7/site-packages/scipy/_lib/_util.py", line 138, in _asarray_validated
    raise ValueError('masked arrays are not supported')
ValueError: masked arrays are not supported

======================================================================
ERROR: test_kalman_pickle (pykalman.tests.test_standard.KalmanFilterTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/tests/test_standard.py", line 183, in test_kalman_pickle
    loglikelihood = kf.loglikelihood(X)
  File "/builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/standard.py", line 1474, in loglikelihood
    predicted_state_means, predicted_state_covariances, Z
  File "/builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/standard.py", line 170, in _loglikelihoods
    predicted_observation_covariance[np.newaxis, :, :]
  File "/builddir/build/BUILD/pykalman-2aeb4ad80f9dcc4ea182331e33bda7ea4866548e/pykalman/utils.py", line 73, in log_multivariate_normal_density
    cv_sol = solve_triangular(cv_chol, (X - mu).T, lower=True).T
  File "/usr/lib64/python2.7/site-packages/scipy/linalg/basic.py", line 155, in solve_triangular
    b1 = _asarray_validated(b, check_finite=check_finite)
  File "/usr/lib64/python2.7/site-packages/scipy/_lib/_util.py", line 138, in _asarray_validated
    raise ValueError('masked arrays are not supported')
ValueError: masked arrays are not supported

----------------------------------------------------------------------
Ran 17 tests in 0.747s

FAILED (errors=2)

```

**Comment by sanjayankur31** [comment]
Also fails with py3:

```
+ /usr/bin/nosetests-3.5 pykalman/tests/
..E./builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/standard.py:1397: UserWarning: transition_offsets has 2 dimensions now; after fitting, it will have dimension 1
  warnings.warn(warn_str)
E............
======================================================================
ERROR: test_kalman_fit (pykalman.tests.test_standard.KalmanFilterTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/tests/test_standard.py", line 128, in test_kalman_fit
    loglikelihoods[i] = kf.loglikelihood(self.data.observations)
  File "/builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/standard.py", line 1474, in loglikelihood
    predicted_state_means, predicted_state_covariances, Z
  File "/builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/standard.py", line 170, in _loglikelihoods
    predicted_observation_covariance[np.newaxis, :, :]
  File "/builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/utils.py", line 73, in log_multivariate_normal_density
    cv_sol = solve_triangular(cv_chol, (X - mu).T, lower=True).T
  File "/usr/lib64/python3.5/site-packages/scipy/linalg/basic.py", line 155, in solve_triangular
    b1 = _asarray_validated(b, check_finite=check_finite)
  File "/usr/lib64/python3.5/site-packages/scipy/_lib/_util.py", line 138, in _asarray_validated
    raise ValueError('masked arrays are not supported')
ValueError: masked arrays are not supported

======================================================================
ERROR: test_kalman_pickle (pykalman.tests.test_standard.KalmanFilterTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/tests/test_standard.py", line 183, in test_kalman_pickle
    loglikelihood = kf.loglikelihood(X)
  File "/builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/standard.py", line 1474, in loglikelihood
    predicted_state_means, predicted_state_covariances, Z
  File "/builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/standard.py", line 170, in _loglikelihoods
    predicted_observation_covariance[np.newaxis, :, :]
  File "/builddir/build/BUILD/python3-python-pykalman-0.9.5-8.20140827git2aeb4ad.fc25/pykalman/utils.py", line 73, in log_multivariate_normal_density
    cv_sol = solve_triangular(cv_chol, (X - mu).T, lower=True).T
  File "/usr/lib64/python3.5/site-packages/scipy/linalg/basic.py", line 155, in solve_triangular
    b1 = _asarray_validated(b, check_finite=check_finite)
  File "/usr/lib64/python3.5/site-packages/scipy/_lib/_util.py", line 138, in _asarray_validated
    raise ValueError('masked arrays are not supported')
ValueError: masked arrays are not supported

----------------------------------------------------------------------
Ran 17 tests in 0.902s

FAILED (errors=2)

```

**Comment by fabiansinz** [comment]
The problem is that `solve_triangular` in `utils.log_multivariate_normal_density` cannot deal with masked arrays. What about replacing the line 
```
cv_sol = solve_triangular(cv_chol, (X - mu).T, lower=True).T
```
by 
```
cv_sol = solve_triangular(cv_chol, (np.ma.compress_rows(X) - mu).T, lower=True).T
```
?
That would drop all rows (data points) with a masked column.
