### ISSUE TITLE
The example of plot_em.py seems has a problem about the datasets.

### ISSUE THREAD

**Issue by Gabrielvon** [pykalman/pykalman#72]
I guess the problem is in kf.loglikelihood(data.observations)

```
# Learn good values for parameters named in `em_vars` using the EM algorithm
loglikelihoods = np.zeros(10)
for i in range(len(loglikelihoods)):
    kf = kf.em(X=data.observations, n_iter=1)
    loglikelihoods[i] = kf.loglikelihood(data.observations)

Traceback (most recent call last):
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-786c67c6a0d9>", line 5, in <module>
    loglikelihoods[i] = kf.loglikelihood(data.observations)
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pykalman/standard.py", line 1474, in loglikelihood
    predicted_state_means, predicted_state_covariances, Z
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pykalman/standard.py", line 170, in _loglikelihoods
    predicted_observation_covariance[np.newaxis, :, :]
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/pykalman/utils.py", line 73, in log_multivariate_normal_density
    cv_sol = solve_triangular(cv_chol, (X - mu).T, lower=True).T
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py", line 284, in solve_triangular
    b1 = _asarray_validated(b, check_finite=check_finite)
  File "/Users/gabrielfeng/anaconda3/lib/python3.6/site-packages/scipy/_lib/_util.py", line 236, in _asarray_validated
    raise ValueError('masked arrays are not supported')
ValueError: masked arrays are not supported

```

**Comment by Gabrielvon** [comment]
Sorry, I just found the solution here. 
[https://github.com/pykalman/pykalman/issues/49](url)

**Comment by Gabrielvon** [comment]
closed issue.
